############################################################################
# app/button_test/Makefile
#
# 按键 GPIO 测试程序构建文件
############################################################################

include $(APPDIR)/Make.defs

# 应用配置
PROGNAME  = $(CONFIG_BUTTON_TEST_PROGNAME)
PRIORITY  = $(CONFIG_BUTTON_TEST_PRIORITY)
STACKSIZE = $(CONFIG_BUTTON_TEST_STACKSIZE)

# 源文件
MAINSRC = button_test_main.c

include $(APPDIR)/Application.mk
