############################################################################
# app/led_test/Makefile
#
# LED GPIO 测试程序构建文件
############################################################################

include $(APPDIR)/Make.defs

# 应用配置
PROGNAME  = $(CONFIG_LED_TEST_PROGNAME)
PRIORITY  = $(CONFIG_LED_TEST_PRIORITY)
STACKSIZE = $(CONFIG_LED_TEST_STACKSIZE)

# 源文件
MAINSRC = led_test_main.c

include $(APPDIR)/Application.mk
